
before_deploy:
- git config --local user.name "Mushware Machine"
- git config --local user.email "machine@mushware.com"
deploy:
  edge: true
  file: MushRuby*.zip
  file_glob: true
  provider: releases
  on:
    tags: true
  overwrite: false
  prerelease: true
  repo: mushware/ruby
  token:
    secure: fxB5lVU2SHSC60TzGvd9ohQ4zmXBs48h7Pkzz9L8w3lehR2g9Y+zxq/Bn0D6glSXOAy6noa/WOsKD+UMpJaTPOchk4S2OQhvDwQdMWQoJqDbqwNDh38t2fFCHfPawLyYTalQgjc/8ZgADSk38V1g4+U5wHMzv/iHfxwZ/6hLp0g9Vw09ZpYk2BAJNB/xoCHRev4Xhp8aWiIffgC5vAW2yFe3qbBD1YGUOXcIA8kAC7e9Y4ZVsdue7IPBhyx8uDP5zl9MhCdCRP6/bNgzuSO+nNnYhe+YtslcUsXcd32T0/YEtcXRmktdEC58WpeTdKv3V9gmvTvOrS96hJWYf59f/RR7cdpSB4VkoUyMYFt3mHYkxzVlWqUdr4s30vCYT6WItx3AnRhhb1YbJNgqVf1uULkti5Gpg0Oss5IfUt+0wGLmSoC48OlsLp+Xe/ZXwlrbLFqvwD5nO3UhDqLCEWQgrt4Bgs+7xuEwhs5yJ5Gr1NTEHECsfCCzdN/vU2Pq2OXM7efmtzJ9IQ6zZhMpMXr51Bj9RyyKwjY/YefUVIbOfWiiYvhz689Y7UnokFQTBLsdKAWPgc1sni6Gp7byqDSiC9Zzs03P/I12XU8UFdnw9Z4P7uNvBRgitWkGJxvp6/bSLuRZLu8GwbilbmqA1POjOIwlIIFlLeQ3mszRy2bAx4g=
env:
- BUILD_CONFIGURATION=Debug
- BUILD_CONFIGURATION=Release
git:
  depth: 3
language: cpp
os: windows
script:
- unset CC
- unset CC_FOR_BUILD
- unset CXX
- unset CXX_FOR_BUILD
- mushware/build_dll_travis.bat
